#!/usr/bin/env php
<?php

define('DS', DIRECTORY_SEPARATOR);

$abs_dir = realpath(__DIR__);

// Initialize autoloaders
require $abs_dir . DS . 'vendor' . DS . 'autoload.php';
require $abs_dir . DS . 'app' . DS . 'classes' . DS . 'FeedAPI' . DS .'Autoload.php';

$autoloader = new FeedAPI\Autoload();
$autoloader->setBasePath($abs_dir . DS . 'app' . DS . 'classes')->register();

$cli = new FeedAPI\CLI\CLI($argv);
$cli->process();
